// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Desk struct {
	ID          uuid.UUID
	Description sql.NullString
	IsActive    bool
	PublicID    string
	Name        string
}

type Purpose struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	PurposeName     string
	ParentPurposeID uuid.NullUUID
	PublicID        string
}

type RefreshToken struct {
	Token        string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ExpiresAt    time.Time
	RevokedAt    sql.NullTime
	PublicID     string
	UserPublicID string
}

type ServiceLog struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CalledAt        time.Time
	IsActive        bool
	PublicID        string
	UserPublicID    string
	VisitorPublicID string
	DeskPublicID    string
}

type TicketCounter struct {
	Date             time.Time
	LastTicketNumber int32
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	IsAdmin        bool
	IsActive       bool
	DeskID         uuid.NullUUID
	FullName       string
	PublicID       string
}

type Visitor struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	WaitingSince      time.Time
	Name              sql.NullString
	Status            int32
	DailyTicketNumber int32
	PublicID          string
	PurposePublicID   string
}
