// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Desk struct {
	ID          uuid.UUID
	Number      int32
	Description sql.NullString
	IsActive    bool
}

type Purpose struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	PurposeName     string
	ParentPurposeID uuid.NullUUID
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type ServiceLog struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	VisitorID uuid.UUID
	UserID    uuid.UUID
	DeskID    uuid.UUID
	CalledAt  time.Time
	IsActive  bool
}

type TicketCounter struct {
	Date             time.Time
	LastTicketNumber int32
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	IsAdmin        bool
	IsActive       bool
	DeskID         uuid.NullUUID
	FullName       string
}

type Visitor struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	WaitingSince      time.Time
	Name              sql.NullString
	PurposeID         uuid.UUID
	Status            int32
	DailyTicketNumber int32
}
