// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: servicelogs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getActiveServiceLogs = `-- name: GetActiveServiceLogs :many
SELECT id, created_at, updated_at, visitor_id, user_id, desk_id, called_at, is_active FROM service_logs
WHERE is_active = true
`

func (q *Queries) GetActiveServiceLogs(ctx context.Context) ([]ServiceLog, error) {
	rows, err := q.db.QueryContext(ctx, getActiveServiceLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceLog
	for rows.Next() {
		var i ServiceLog
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VisitorID,
			&i.UserID,
			&i.DeskID,
			&i.CalledAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveServiceLogsByUserID = `-- name: GetActiveServiceLogsByUserID :one
SELECT id, created_at, updated_at, visitor_id, user_id, desk_id, called_at, is_active FROM service_logs
where is_active = true AND user_id = $1
`

func (q *Queries) GetActiveServiceLogsByUserID(ctx context.Context, userID uuid.UUID) (ServiceLog, error) {
	row := q.db.QueryRowContext(ctx, getActiveServiceLogsByUserID, userID)
	var i ServiceLog
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisitorID,
		&i.UserID,
		&i.DeskID,
		&i.CalledAt,
		&i.IsActive,
	)
	return i, err
}

const getServiceLogs = `-- name: GetServiceLogs :many
SELECT id, created_at, updated_at, visitor_id, user_id, desk_id, called_at, is_active FROM service_logs
`

func (q *Queries) GetServiceLogs(ctx context.Context) ([]ServiceLog, error) {
	rows, err := q.db.QueryContext(ctx, getServiceLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceLog
	for rows.Next() {
		var i ServiceLog
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VisitorID,
			&i.UserID,
			&i.DeskID,
			&i.CalledAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
