// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: ticket_counter.sql

package database

import (
	"context"
)

const update_ticket_counter = `-- name: update_ticket_counter :one
INSERT INTO ticket_counter (counter_date, last_ticket_number)
VALUES (CURRENT_DATE, 1)
ON CONFLICT (counter_date)
DO UPDATE SET
  last_ticket_number = ticket_counter.last_ticket_number + 1
RETURNING last_ticket_number
`

func (q *Queries) update_ticket_counter(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, update_ticket_counter)
	var last_ticket_number int32
	err := row.Scan(&last_ticket_number)
	return last_ticket_number, err
}
