// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: ticket_counter.sql

package database

import (
	"context"
)

const updateTicketCounter = `-- name: UpdateTicketCounter :one
INSERT INTO ticket_counter (counter_date, last_ticket_number)
VALUES (CURRENT_DATE, 1)
ON CONFLICT (counter_date)
DO UPDATE SET
  last_ticket_number = ticket_counter.last_ticket_number + 1
RETURNING last_ticket_number
`

func (q *Queries) UpdateTicketCounter(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateTicketCounter)
	var last_ticket_number int32
	err := row.Scan(&last_ticket_number)
	return last_ticket_number, err
}
