// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_password, full_name, is_admin, is_active)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    FALSE,
    TRUE
)
RETURNING id, created_at, updated_at, email, hashed_password, is_admin, is_active, desk_id, full_name
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
	FullName       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPassword, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsAdmin,
		&i.IsActive,
		&i.DeskID,
		&i.FullName,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :one
DELETE FROM users
WHERE id = $1
RETURNING id, created_at, updated_at, email, hashed_password, is_admin, is_active, desk_id, full_name
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsAdmin,
		&i.IsActive,
		&i.DeskID,
		&i.FullName,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, email, hashed_password, is_admin, is_active, desk_id, full_name FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsAdmin,
		&i.IsActive,
		&i.DeskID,
		&i.FullName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, email, hashed_password, is_admin, is_active, desk_id, full_name FROM users
where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsAdmin,
		&i.IsActive,
		&i.DeskID,
		&i.FullName,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, created_at, updated_at, email, hashed_password, is_admin, is_active, desk_id, full_name FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.HashedPassword,
			&i.IsAdmin,
			&i.IsActive,
			&i.DeskID,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmailPasswordByID = `-- name: SetEmailPasswordByID :one
UPDATE users
SET email = $2, hashed_password = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, email, hashed_password, is_admin, is_active, desk_id, full_name
`

type SetEmailPasswordByIDParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

func (q *Queries) SetEmailPasswordByID(ctx context.Context, arg SetEmailPasswordByIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setEmailPasswordByID, arg.ID, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsAdmin,
		&i.IsActive,
		&i.DeskID,
		&i.FullName,
	)
	return i, err
}

const setFullNameByID = `-- name: SetFullNameByID :one
UPDATE users
SET full_name = $2
where id = $1
RETURNING id, created_at, updated_at, email, hashed_password, is_admin, is_active, desk_id, full_name
`

type SetFullNameByIDParams struct {
	ID       uuid.UUID
	FullName string
}

func (q *Queries) SetFullNameByID(ctx context.Context, arg SetFullNameByIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setFullNameByID, arg.ID, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsAdmin,
		&i.IsActive,
		&i.DeskID,
		&i.FullName,
	)
	return i, err
}

const setInactiveByID = `-- name: SetInactiveByID :one
UPDATE users
SET is_active = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, email, hashed_password, is_admin, is_active, desk_id, full_name
`

type SetInactiveByIDParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) SetInactiveByID(ctx context.Context, arg SetInactiveByIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setInactiveByID, arg.ID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsAdmin,
		&i.IsActive,
		&i.DeskID,
		&i.FullName,
	)
	return i, err
}

const setIsAdminByID = `-- name: SetIsAdminByID :one
UPDATE users
SET is_admin = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, email, hashed_password, is_admin, is_active, desk_id, full_name
`

type SetIsAdminByIDParams struct {
	ID      uuid.UUID
	IsAdmin bool
}

func (q *Queries) SetIsAdminByID(ctx context.Context, arg SetIsAdminByIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setIsAdminByID, arg.ID, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsAdmin,
		&i.IsActive,
		&i.DeskID,
		&i.FullName,
	)
	return i, err
}
