// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: visitors.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createVisitor = `-- name: CreateVisitor :one
INSERT INTO visitors (id, created_at, updated_at, waiting_since, name, purpose, status)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    NOW(),
    $1,
    $2,
    0
)
RETURNING id, created_at, updated_at, waiting_since, name, purpose, status
`

type CreateVisitorParams struct {
	Name    sql.NullString
	Purpose string
}

func (q *Queries) CreateVisitor(ctx context.Context, arg CreateVisitorParams) (Visitor, error) {
	row := q.db.QueryRowContext(ctx, createVisitor, arg.Name, arg.Purpose)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WaitingSince,
		&i.Name,
		&i.Purpose,
		&i.Status,
	)
	return i, err
}

const getVisitorByID = `-- name: GetVisitorByID :one
SELECT id, created_at, updated_at, waiting_since, name, purpose, status FROM visitors
WHERE id = $1
`

func (q *Queries) GetVisitorByID(ctx context.Context, id uuid.UUID) (Visitor, error) {
	row := q.db.QueryRowContext(ctx, getVisitorByID, id)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WaitingSince,
		&i.Name,
		&i.Purpose,
		&i.Status,
	)
	return i, err
}

const getVisitorsByStatus = `-- name: GetVisitorsByStatus :many
SELECT id, created_at, updated_at, waiting_since, name, purpose, status FROM visitors
WHERE status = $1
ORDER BY waiting_since ASC
`

func (q *Queries) GetVisitorsByStatus(ctx context.Context, status int32) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getVisitorsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WaitingSince,
			&i.Name,
			&i.Purpose,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisitorsForToday = `-- name: GetVisitorsForToday :many
SELECT id, created_at, updated_at, waiting_since, name, purpose, status FROM visitors
WHERE waiting_since::date = CURRENT_DATE
ORDER BY waiting_since ASC
`

func (q *Queries) GetVisitorsForToday(ctx context.Context) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getVisitorsForToday)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WaitingSince,
			&i.Name,
			&i.Purpose,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWaitingVisitorsByPurpose = `-- name: GetWaitingVisitorsByPurpose :many
SELECT id, created_at, updated_at, waiting_since, name, purpose, status FROM visitors
WHERE purpose = $1 AND status = 1
ORDER BY waiting_since ASC
`

func (q *Queries) GetWaitingVisitorsByPurpose(ctx context.Context, purpose string) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getWaitingVisitorsByPurpose, purpose)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WaitingSince,
			&i.Name,
			&i.Purpose,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVisitorByID = `-- name: SetVisitorByID :one
UPDATE visitors
SET name = $2, purpose = $3, status = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, waiting_since, name, purpose, status
`

type SetVisitorByIDParams struct {
	ID      uuid.UUID
	Name    sql.NullString
	Purpose string
	Status  int32
}

func (q *Queries) SetVisitorByID(ctx context.Context, arg SetVisitorByIDParams) (Visitor, error) {
	row := q.db.QueryRowContext(ctx, setVisitorByID,
		arg.ID,
		arg.Name,
		arg.Purpose,
		arg.Status,
	)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WaitingSince,
		&i.Name,
		&i.Purpose,
		&i.Status,
	)
	return i, err
}

const setVisitorStatusByID = `-- name: SetVisitorStatusByID :one
UPDATE visitors
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, waiting_since, name, purpose, status
`

type SetVisitorStatusByIDParams struct {
	ID     uuid.UUID
	Status int32
}

func (q *Queries) SetVisitorStatusByID(ctx context.Context, arg SetVisitorStatusByIDParams) (Visitor, error) {
	row := q.db.QueryRowContext(ctx, setVisitorStatusByID, arg.ID, arg.Status)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WaitingSince,
		&i.Name,
		&i.Purpose,
		&i.Status,
	)
	return i, err
}
