// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: visitors.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createVisitor = `-- name: CreateVisitor :one
INSERT INTO visitors (id, public_id, created_at, updated_at, waiting_since, name, purpose_public_id, status, daily_ticket_number)
VALUES (
    gen_random_uuid(),
    $1,
    NOW(),
    NOW(),
    NOW(),
    $2,
    $3,
    0, --status 
    $4
)
RETURNING id, created_at, updated_at, waiting_since, name, status, daily_ticket_number, public_id, purpose_public_id
`

type CreateVisitorParams struct {
	PublicID          string
	Name              sql.NullString
	PurposePublicID   string
	DailyTicketNumber int32
}

func (q *Queries) CreateVisitor(ctx context.Context, arg CreateVisitorParams) (Visitor, error) {
	row := q.db.QueryRowContext(ctx, createVisitor,
		arg.PublicID,
		arg.Name,
		arg.PurposePublicID,
		arg.DailyTicketNumber,
	)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WaitingSince,
		&i.Name,
		&i.Status,
		&i.DailyTicketNumber,
		&i.PublicID,
		&i.PurposePublicID,
	)
	return i, err
}

const getVisitorByID = `-- name: GetVisitorByID :one
SELECT id, created_at, updated_at, waiting_since, name, status, daily_ticket_number, public_id, purpose_public_id FROM visitors
WHERE visitors.id = $1
`

func (q *Queries) GetVisitorByID(ctx context.Context, id uuid.UUID) (Visitor, error) {
	row := q.db.QueryRowContext(ctx, getVisitorByID, id)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WaitingSince,
		&i.Name,
		&i.Status,
		&i.DailyTicketNumber,
		&i.PublicID,
		&i.PurposePublicID,
	)
	return i, err
}

const getVisitors = `-- name: GetVisitors :many
SELECT id, created_at, updated_at, waiting_since, name, status, daily_ticket_number, public_id, purpose_public_id FROM visitors
`

func (q *Queries) GetVisitors(ctx context.Context) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getVisitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WaitingSince,
			&i.Name,
			&i.Status,
			&i.DailyTicketNumber,
			&i.PublicID,
			&i.PurposePublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisitorsByPublicID = `-- name: GetVisitorsByPublicID :one
SELECT id, created_at, updated_at, waiting_since, name, status, daily_ticket_number, public_id, purpose_public_id FROM visitors
WHERE public_id = $1
`

func (q *Queries) GetVisitorsByPublicID(ctx context.Context, publicID string) (Visitor, error) {
	row := q.db.QueryRowContext(ctx, getVisitorsByPublicID, publicID)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WaitingSince,
		&i.Name,
		&i.Status,
		&i.DailyTicketNumber,
		&i.PublicID,
		&i.PurposePublicID,
	)
	return i, err
}

const getVisitorsByPurposePublicID = `-- name: GetVisitorsByPurposePublicID :many
SELECT id, created_at, updated_at, waiting_since, name, status, daily_ticket_number, public_id, purpose_public_id FROM visitors
WHERE purpose_public_id = $1
ORDER BY waiting_since ASC
`

func (q *Queries) GetVisitorsByPurposePublicID(ctx context.Context, purposePublicID string) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getVisitorsByPurposePublicID, purposePublicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WaitingSince,
			&i.Name,
			&i.Status,
			&i.DailyTicketNumber,
			&i.PublicID,
			&i.PurposePublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisitorsByPurposePublicIDAndStatus = `-- name: GetVisitorsByPurposePublicIDAndStatus :many
SELECT id, created_at, updated_at, waiting_since, name, status, daily_ticket_number, public_id, purpose_public_id FROM visitors
WHERE purpose_public_id = $1 AND status = $2
ORDER BY waiting_since ASC
`

type GetVisitorsByPurposePublicIDAndStatusParams struct {
	PurposePublicID string
	Status          int32
}

func (q *Queries) GetVisitorsByPurposePublicIDAndStatus(ctx context.Context, arg GetVisitorsByPurposePublicIDAndStatusParams) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getVisitorsByPurposePublicIDAndStatus, arg.PurposePublicID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WaitingSince,
			&i.Name,
			&i.Status,
			&i.DailyTicketNumber,
			&i.PublicID,
			&i.PurposePublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisitorsByStatus = `-- name: GetVisitorsByStatus :many
SELECT id, created_at, updated_at, waiting_since, name, status, daily_ticket_number, public_id, purpose_public_id FROM visitors
WHERE status = $1 -- status
ORDER BY waiting_since ASC
`

func (q *Queries) GetVisitorsByStatus(ctx context.Context, status int32) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getVisitorsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WaitingSince,
			&i.Name,
			&i.Status,
			&i.DailyTicketNumber,
			&i.PublicID,
			&i.PurposePublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisitorsForToday = `-- name: GetVisitorsForToday :many
SELECT id, created_at, updated_at, waiting_since, name, status, daily_ticket_number, public_id, purpose_public_id FROM visitors
WHERE waiting_since::date = CURRENT_DATE
ORDER BY waiting_since ASC
`

func (q *Queries) GetVisitorsForToday(ctx context.Context) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getVisitorsForToday)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WaitingSince,
			&i.Name,
			&i.Status,
			&i.DailyTicketNumber,
			&i.PublicID,
			&i.PurposePublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWaitingVisitorsByPurposePublicID = `-- name: GetWaitingVisitorsByPurposePublicID :many
SELECT id, created_at, updated_at, waiting_since, name, status, daily_ticket_number, public_id, purpose_public_id FROM visitors 
WHERE purpose_public_id = $1 AND status = 1 -- NOTE that statuses are still not properly implemented
ORDER BY waiting_since ASC
`

func (q *Queries) GetWaitingVisitorsByPurposePublicID(ctx context.Context, purposePublicID string) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getWaitingVisitorsByPurposePublicID, purposePublicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WaitingSince,
			&i.Name,
			&i.Status,
			&i.DailyTicketNumber,
			&i.PublicID,
			&i.PurposePublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitors = `-- name: ListVisitors :many
SELECT id, created_at, updated_at, waiting_since, name, status, daily_ticket_number, public_id, purpose_public_id FROM visitors
WHERE ($1::int IS NULL OR status = $1)
    AND ($2::text IS NULL OR purpose_public_id = $2)
    AND ($3::timestamp IS NULL OR created_at >= $3)
    AND ($4::timestamp IS NULL OR created_at < $4)
ORDER BY waiting_since ASC
`

type ListVisitorsParams struct {
	Status          sql.NullInt32
	PurposePublicID sql.NullString
	StartDate       sql.NullTime
	EndDate         sql.NullTime
}

func (q *Queries) ListVisitors(ctx context.Context, arg ListVisitorsParams) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, listVisitors,
		arg.Status,
		arg.PurposePublicID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WaitingSince,
			&i.Name,
			&i.Status,
			&i.DailyTicketNumber,
			&i.PublicID,
			&i.PurposePublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVisitorByPublicID = `-- name: SetVisitorByPublicID :one
UPDATE visitors
SET name = $2, purpose_public_id = $3, status = $4, updated_at = NOW() -- status
WHERE public_id = $1
RETURNING id, created_at, updated_at, waiting_since, name, status, daily_ticket_number, public_id, purpose_public_id
`

type SetVisitorByPublicIDParams struct {
	PublicID        string
	Name            sql.NullString
	PurposePublicID string
	Status          int32
}

func (q *Queries) SetVisitorByPublicID(ctx context.Context, arg SetVisitorByPublicIDParams) (Visitor, error) {
	row := q.db.QueryRowContext(ctx, setVisitorByPublicID,
		arg.PublicID,
		arg.Name,
		arg.PurposePublicID,
		arg.Status,
	)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WaitingSince,
		&i.Name,
		&i.Status,
		&i.DailyTicketNumber,
		&i.PublicID,
		&i.PurposePublicID,
	)
	return i, err
}

const setVisitorStatusByID = `-- name: SetVisitorStatusByID :one
UPDATE visitors
SET status = $2, updated_at = NOW() --status 
WHERE id = $1
RETURNING id, created_at, updated_at, waiting_since, name, status, daily_ticket_number, public_id, purpose_public_id
`

type SetVisitorStatusByIDParams struct {
	ID     uuid.UUID
	Status int32
}

func (q *Queries) SetVisitorStatusByID(ctx context.Context, arg SetVisitorStatusByIDParams) (Visitor, error) {
	row := q.db.QueryRowContext(ctx, setVisitorStatusByID, arg.ID, arg.Status)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WaitingSince,
		&i.Name,
		&i.Status,
		&i.DailyTicketNumber,
		&i.PublicID,
		&i.PurposePublicID,
	)
	return i, err
}
